# action.yml
name: 'Algorithmia CI'
description: 'End-to-end Continuous Integration & Deployment for Algorithms on Algorithmia.com'
branding:
  icon: 'alert-circle'
  color: 'purple'
inputs:
  api_key:
    description: 'Your master Algorithmia API key'
    required: true
  api_address:
    description: 'The API address for the Algorithmia Cluster you wish to connect to'
    required: false
    default: 'https://api.algorithmia.com'
  version_schema:
    description: 'identifier to describe how to promote this release'
    required: false
    default: "minor"

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.api_key }}
    - ${{ inputs.api_address }}
    - ${{ inputs.version_schema }}
